<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>@yield('title')</title>
    <style>
        * { box-sizing: border-box; }
        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #1a1a1a;
            margin: 0;
        }
        .header { border-bottom: 2px solid #1a1a1a; padding-bottom: 12px; margin-bottom: 18px; }
        .brand { font-size: 20px; font-weight: bold; letter-spacing: 0.5px; }
        .brand-sub { color: #666; font-size: 10px; margin-top: 2px; }
        .doc-title { font-size: 16px; font-weight: bold; text-align: right; margin-top: -34px; }
        .doc-number { text-align: right; color: #666; font-size: 11px; }
        .meta { width: 100%; margin-bottom: 18px; }
        .meta td { vertical-align: top; padding: 0; width: 50%; }
        .label { color: #666; font-size: 10px; text-transform: uppercase; letter-spacing: 0.4px; }
        .value { font-weight: bold; }
        table.lines { width: 100%; border-collapse: collapse; margin-top: 6px; }
        table.lines th {
            background: #f2f2f2;
            text-align: left;
            padding: 6px 8px;
            border-bottom: 1px solid #ccc;
            font-size: 10px;
            text-transform: uppercase;
        }
        table.lines td { padding: 6px 8px; border-bottom: 1px solid #eee; }
        .right { text-align: right; }
        .totals { width: 46%; margin-left: 54%; margin-top: 14px; }
        .totals td { padding: 4px 8px; }
        .totals .grand { border-top: 2px solid #1a1a1a; font-weight: bold; font-size: 13px; }
        .status {
            display: inline-block;
            padding: 2px 8px;
            border: 1px solid #1a1a1a;
            font-size: 10px;
            text-transform: uppercase;
        }
        .footer {
            position: fixed;
            bottom: 0;
            width: 100%;
            border-top: 1px solid #ddd;
            padding-top: 6px;
            color: #888;
            font-size: 9px;
        }
    </style>
</head>
<body>
    <div class="header">
        <div class="brand">LedgerCraft</div>
        <div class="brand-sub">Urban Furniture</div>
        <div class="doc-title">@yield('doc-title')</div>
        <div class="doc-number">@yield('doc-number')</div>
    </div>

    @yield('content')

    <div class="footer">
        Generated by LedgerCraft on {{ now()->format('d M Y H:i') }}
    </div>
</body>
</html>
